# Generated by Django 3.0.3 on 2020-08-24 01:17

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('dong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('gu', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('user_pw', models.CharField(max_length=300)),
                ('nick_name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(blank=True, null=True)),
                ('last_date', models.DateTimeField(blank=True, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='User')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Memberaddr',
            fields=[
                ('id_member_addr', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=200)),
                ('distance', models.IntegerField(default=0)),
                ('select', models.CharField(default='Y', max_length=8)),
            ],
            options={
                'db_table': 'member_addr',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id_rate', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=8)),
                ('detail', models.CharField(max_length=50)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='RealDeal',
            fields=[
                ('id_real_deal', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'real_deal',
            },
        ),
        migrations.CreateModel(
            name='SellerRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'seller_rate',
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id_review_seller', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller_review',
            },
        ),
        migrations.CreateModel(
            name='ShopperRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'shopper_rate',
            },
        ),
        migrations.CreateModel(
            name='ShopperReview',
            fields=[
                ('id_review_shopper', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shopper_review',
            },
        ),
        migrations.CreateModel(
            name='NearbyLocation',
            fields=[
                ('dong', models.OneToOneField(db_column='dong', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='common.Location')),
                ('nearby_dong', models.CharField(max_length=20)),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'nearby_location',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id_wishlist', models.AutoField(primary_key=True, serialize=False)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.PROTECT, to='common.Member')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
    ]
