# Generated by Django 3.0.3 on 2020-08-04 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('dong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('gu', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('user_pw', models.CharField(max_length=300)),
                ('nick_name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(null=True)),
                ('last_date', models.DateTimeField(null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=3000)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('views', models.IntegerField(default=0)),
                ('state', models.CharField(default='판매중', max_length=10)),
                ('addr', models.CharField(max_length=200)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.CASCADE, to='common.Member')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id_rate', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=8)),
                ('detail', models.CharField(max_length=50)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='RealDeal',
            fields=[
                ('id_real_deal', models.AutoField(primary_key=True, serialize=False)),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Product')),
            ],
            options={
                'db_table': 'real_deal',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id_wishlist', models.AutoField(primary_key=True, serialize=False)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.PROTECT, to='common.Member')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.PROTECT, to='common.Product')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='ShopperReview',
            fields=[
                ('id_review_shopper', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_real_deal', models.ForeignKey(db_column='id_real_deal', on_delete=django.db.models.deletion.DO_NOTHING, to='common.RealDeal')),
            ],
            options={
                'db_table': 'shopper_review',
            },
        ),
        migrations.CreateModel(
            name='ShopperRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rate', models.ForeignKey(db_column='id_rate', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Rate')),
                ('id_review_shopper', models.ForeignKey(db_column='id_review_shopper', on_delete=django.db.models.deletion.DO_NOTHING, to='common.ShopperReview')),
            ],
            options={
                'db_table': 'shopper_rate',
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id_review_seller', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_seller', models.ForeignKey(db_column='id_seller', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member')),
            ],
            options={
                'db_table': 'seller_review',
            },
        ),
        migrations.CreateModel(
            name='SellerRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rate', models.ForeignKey(db_column='id_rate', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Rate')),
                ('id_review_seller', models.ForeignKey(db_column='id_review_seller', on_delete=django.db.models.deletion.DO_NOTHING, to='common.SellerReview')),
            ],
            options={
                'db_table': 'seller_rate',
            },
        ),
        migrations.AddField(
            model_name='realdeal',
            name='id_review_seller',
            field=models.ForeignKey(db_column='id_review_seller', on_delete=django.db.models.deletion.DO_NOTHING, to='common.SellerReview'),
        ),
        migrations.AddField(
            model_name='realdeal',
            name='id_shopper',
            field=models.ForeignKey(db_column='id_shopper', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member'),
        ),
        migrations.CreateModel(
            name='Memberaddr',
            fields=[
                ('id_member_addr', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=200)),
                ('distance', models.IntegerField(default=0)),
                ('select', models.CharField(default='Y', max_length=8)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member')),
            ],
            options={
                'db_table': 'member_addr',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('info', models.CharField(blank=True, max_length=3000, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('img', models.CharField(blank=True, max_length=2000, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='NearbyLocation',
            fields=[
                ('dong', models.OneToOneField(db_column='dong', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='common.Location')),
                ('nearby_dong', models.CharField(max_length=20)),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'nearby_location',
                'unique_together': {('dong', 'nearby_dong', 'distance')},
            },
        ),
    ]
