# Generated by Django 3.0.3 on 2020-08-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='id_product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.PROTECT, to='posts.Product'),
        ),
        migrations.AddField(
            model_name='shopperreview',
            name='id_real_deal',
            field=models.ForeignKey(db_column='id_real_deal', on_delete=django.db.models.deletion.DO_NOTHING, to='common.RealDeal'),
        ),
        migrations.AddField(
            model_name='shopperrate',
            name='id_rate',
            field=models.ForeignKey(db_column='id_rate', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Rate'),
        ),
        migrations.AddField(
            model_name='shopperrate',
            name='id_review_shopper',
            field=models.ForeignKey(db_column='id_review_shopper', on_delete=django.db.models.deletion.DO_NOTHING, to='common.ShopperReview'),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='id_seller',
            field=models.ForeignKey(db_column='id_seller', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member'),
        ),
        migrations.AddField(
            model_name='sellerrate',
            name='id_rate',
            field=models.ForeignKey(db_column='id_rate', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Rate'),
        ),
        migrations.AddField(
            model_name='sellerrate',
            name='id_review_seller',
            field=models.ForeignKey(db_column='id_review_seller', on_delete=django.db.models.deletion.DO_NOTHING, to='common.SellerReview'),
        ),
        migrations.AddField(
            model_name='realdeal',
            name='id_product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Product'),
        ),
        migrations.AddField(
            model_name='realdeal',
            name='id_review_seller',
            field=models.ForeignKey(db_column='id_review_seller', on_delete=django.db.models.deletion.DO_NOTHING, to='common.SellerReview'),
        ),
        migrations.AddField(
            model_name='realdeal',
            name='id_shopper',
            field=models.ForeignKey(db_column='id_shopper', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member'),
        ),
        migrations.AddField(
            model_name='memberaddr',
            name='id_member',
            field=models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='nearbylocation',
            unique_together={('dong', 'nearby_dong', 'distance')},
        ),
    ]
