# Generated by Django 3.0.3 on 2020-08-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_create_category_code'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.ForeignKey(default='ETC', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_code', to='posts.CategoryCode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_member',
            field=models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.CASCADE, related_name='product_member', to='common.Member'),
        ),
    ]
