# Generated by Django 3.0.3 on 2020-08-08 20:08

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_product_rename_field_category_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='img',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='User'),
        ),
        migrations.AlterField(
            model_name='location',
            name='gu',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('SALE', '판매중'), ('BOOKING', '예약중'), ('COMPLETED', '거래완료'), ('HIDE', '숨기기')], default='SALE', max_length=10),
        ),
    ]
