# Generated by Django 3.0.3 on 2020-08-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200808_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
