# Generated by Django 3.0.3 on 2020-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_log_manner_mannerlog_mannerreviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gu',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
