# Generated by Django 3.0.3 on 2020-08-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_log_manner_mannerlog_mannerreviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbylocation',
            name='dong',
            field=models.ForeignKey(db_column='dong', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Location'),
        ),
        migrations.AddField(
            model_name='nearbylocation',
            name='id_nearby_location',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='gu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
