# Generated by Django 3.0.3 on 2020-08-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200809_0311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
