# Generated by Django 3.0.3 on 2020-08-30 18:22

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_nearby_location_dong_foreignkey_for_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='member'),
        ),
    ]
