# Generated by Django 3.0.3 on 2020-08-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='udate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
