# Generated by Django 3.0.3 on 2020-08-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_member_field_add_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='udate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
