# Generated by Django 3.0.3 on 2020-09-01 19:32

import common.models.member_model
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200831_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=common.models.member_model.Member.upload_to_id_image),
        ),
    ]
