# Generated by Django 3.0.7 on 2020-09-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_member_field_image_udate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannerlog',
            name='reviewer',
            field=models.ForeignKey(db_column='reviewer', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member'),
        ),
        migrations.DeleteModel(
            name='MannerReviewer',
        ),
    ]
