# Generated by Django 3.0.3 on 2020-08-24 01:17

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCode',
            fields=[
                ('category', models.CharField(choices=[('PRODUCT', 'Product'), ('PROMOTION', 'Promotion')], default='PRODUCT', max_length=20)),
                ('code', models.CharField(choices=[('ELECTRONICS', '디지털/가전'), ('FURNITURE', '가구/인테리어'), ('INFANT', '유아동/유아도서'), ('DAILY', '생활/가공식품'), ('SPORTS', '스포츠/레저'), ('WOMEN-GOODS', '여성잡화'), ('WOMEN-FASHION', '여성의류'), ('MEN', '남성팬션/잡화'), ('GAME', '게임/취미'), ('BEAUTY', '뷰티/미용'), ('PET', '반려동물용품'), ('CULTURE', '도서/티켓/음반'), ('ETC', '기타 중고물품')], db_column='code', default='ETC', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'posts_category_code',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=3000)),
                ('views', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('SALE', '판매중'), ('BOOKING', '예약중'), ('COMPLETED', '거래완료'), ('HIDE', '숨기기')], default='SALE', max_length=10)),
                ('addr', models.CharField(max_length=200)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(db_column='code', default='ETC', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_code', to='posts.CategoryCode')),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.CASCADE, related_name='product_member', to='common.Member')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id_product_img', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='product')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='thum', to='posts.Product')),
            ],
            options={
                'db_table': 'posts_product_image',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('info', models.CharField(blank=True, max_length=3000, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('img', models.CharField(blank=True, max_length=2000, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
