# Generated by Django 3.0.3 on 2020-08-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_create_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycode',
            name='category',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('PROMOTION', 'Promotion')], default='PRODUCT', max_length=20),
        ),
    ]
