# Generated by Django 3.0.3 on 2020-08-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_categorycode_text-choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='title',
            new_name='image_title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.ForeignKey(default='ETC', on_delete=django.db.models.deletion.DO_NOTHING, to='posts.CategoryCode'),
        ),
    ]
