# Generated by Django 3.0.3 on 2020-08-09 17:01

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_delete_company'),
        ('posts', '0002_auto_20200808_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id_product_img', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='product')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='thum', to='common.Product')),
            ],
            options={
                'db_table': 'posts_product_image',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('info', models.CharField(blank=True, max_length=3000, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('img', models.CharField(blank=True, max_length=2000, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Member')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
