# Generated by Django 3.0.3 on 2020-09-01 19:32

from django.db import migrations, models
import imagekit.models.fields
import posts.models.posts_product_image_model


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200831_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.models.posts_product_image_model.ProductImage.upload_to_id_image),
        ),
    ]
